let food = {
  menuName: "Pizza Paradise",
  version: "1.0",
  pizzas: [
    {
      id: "p001",
      name: "Margherita Classic",
      category: "veg",
      price: 9.99,
      toppings: ["Cheese", "Tomato Sauce", "Basil"],
      isSpicy: false,
      img: "https://images.unsplash.com/photo-1601924582975-7e1f1a3dacfb",
      desc: "A timeless Italian favorite topped with fresh basil, rich tomato sauce, and mozzarella.",
    },
    {
      id: "p014",
      name: "Chicken Ranch ",
      category: "non-veg",
      price: 15.99,
      toppings: ["Buffalo Chicken", "Ranch Drizzle", "Scallions"],
      isSpicy: true,
      img: "https://images.unsplash.com/photo-1601924638867-3ec4e6b4d8da",
      desc: "Spicy buffalo chicken paired with a creamy ranch drizzle for the perfect flavor burst.",
    },
    {
      id: "p005",
      name: "Veggie Supreme",
      category: "veg",
      price: 14.5,
      toppings: ["Zucchini", "Broccoli", "Spinach", "Artichoke Hearts"],
      isSpicy: false,
      img: "https://images.unsplash.com/photo-1594007654729-407eedc4be3f",
      desc: "A garden-fresh pizza loaded with crunchy veggies and melty cheese.",
    },
    {
      id: "p008",
      name: "Classic Pepperoni",
      category: "non-veg",
      price: 13.99,
      toppings: ["Pepperoni", "Mozzarella", "Tomato Sauce"],
      isSpicy: false,
      img: "https://images.unsplash.com/photo-1601924948338-0675ff8d6ef2",
      desc: "A classic crowd-pleaser topped with crispy pepperoni and gooey mozzarella.",
    },
    {
      id: "p006",
      name: "Jalapeño Popper",
      category: "veg",
      price: 10.99,
      toppings: ["Cream Cheese", "Jalapeños", "Onion"],
      isSpicy: true,
      img: "https://images.unsplash.com/photo-1588165039294-7f1c1f72733d",
      desc: "A spicy twist inspired by jalapeño poppers with creamy cheese and bold heat.",
    },
    {
      id: "p009",
      name: "BBQ Chicken Feast",
      category: "non-veg",
      price: 15.5,
      toppings: ["BBQ Chicken", "Red Onion", "Cheddar"],
      isSpicy: false,
      img: "https://images.unsplash.com/photo-1574126154517-d5d444456e73",
      desc: "Sweet and smoky BBQ chicken with cheddar and onions, baked to perfection.",
    },
    {
      id: "p007",
      name: "Tandoori Soya",
      category: "veg",
      price: 12.0,
      toppings: ["Soya Chaap", "Tandoori Sauce", "Red Onion"],
      isSpicy: true,
      img: "https://images.unsplash.com/photo-1586190848861-99aa4a171e90",
      desc: "A fusion favorite featuring marinated soya chaap and bold tandoori spices.",
    },
    {
      id: "p010",
      name: "Spicy Italian Sausage",
      category: "non-veg",
      price: 14.99,
      toppings: ["Italian Sausage", "Roasted Garlic", "Bell Peppers"],
      isSpicy: true,
      img: "https://images.unsplash.com/photo-1543169018-b2a632c0d832",
      desc: "Loaded with spicy Italian sausage, garlic, and peppers for a fiery flavor.",
    },
    {
      id: "p011",
      name: "Meat Lover's Delight",
      category: "non-veg",
      price: 17.99,
      toppings: ["Pepperoni", "Sausage", "Bacon", "Ham"],
      isSpicy: false,
      img: "https://images.unsplash.com/photo-1564936281403-7d40a6bde02d",
      desc: "The ultimate protein-packed pizza stacked with four types of meat.",
    },
    {
      id: "p012",
      name: "Chicken Tikka Masala",
      category: "non-veg",
      price: 16.5,
      toppings: ["Chicken Tikka", "Curry Sauce", "Fenugreek"],
      isSpicy: true,
      img: "https://images.unsplash.com/photo-1596766736280-c529f5f02f90",
      desc: "A fusion of Indian tikka flavors and classic pizza goodness.",
    },
    {
      id: "p003",
      name: "Farmhouse Fresh",
      category: "veg",
      price: 11.99,
      toppings: ["Mushroom", "Bell Peppers", "Olives", "Corn"],
      isSpicy: false,
      img: "https://images.unsplash.com/photo-1513104890138-7c749659a591",
      desc: "A rustic veggie pizza topped with mushrooms, peppers, olives, and sweet corn.",
    },
    {
      id: "p004",
      name: "Double Cheese Burst",
      category: "veg",
      price: 13.99,
      toppings: ["Extra Mozzarella", "Cheddar", "Tomato Sauce"],
      isSpicy: false,
      img: "https://images.unsplash.com/photo-1594308892794-d2e339f4089a",
      desc: "A cheese lover’s dream featuring double layers of melted cheesy goodness.",
    },
    {
      id: "p013",
      name: "Hawaiian Punch",
      category: "non-veg",
      price: 13.5,
      toppings: ["Ham", "Pineapple", "Red Onion"],
      isSpicy: false,
      img: "https://images.unsplash.com/photo-1601924739536-5e99ef0401d3",
      desc: "A sweet and savory delight with pineapple chunks and smoked ham.",
    },
    {
      id: "p002",
      name: "Spicy Paneer Tikka",
      category: "veg",
      price: 12.5,
      toppings: ["Paneer Tikka", "Onion", "Capsicum", "Cilantro"],
      isSpicy: true,
      img: "https://images.unsplash.com/photo-1579751717208-142c11438b4d",
      desc: "An Indian-inspired pizza topped with spicy paneer tikka and fresh veggies.",
    },
    {
      id: "p015",
      name: "Seafood Special",
      category: "non-veg",
      price: 18.99,
      toppings: ["Shrimp", "Clams", "Garlic Butter Sauce"],
      isSpicy: false,
      img: "https://images.unsplash.com/photo-1542281286-9e0a16bb7366",
      desc: "A rich seafood treat featuring shrimp and clams in a garlic butter sauce.",
    },
  ],
};
